Add proguard-rules to suppress the missing class warning
We have few missing classes warning when building Android apk.  We can suppress that with progurard-rules.

ERROR: R8: Missing class java.awt.event.ActionListener (referenced from: void kotlinx.coroutines.swing.Swing.<clinit>() and 3 other contexts)
Missing class javax.swing.SwingUtilities (referenced from: boolean kotlinx.coroutines.swing.ImmediateSwingDispatcher.isDispatchNeeded(kotlin.coroutines.CoroutineContext) and 1 other context)
Missing class javax.swing.Timer (referenced from: javax.swing.Timer kotlinx.coroutines.swing.SwingDispatcher$scheduleResumeAfterDelay$1.$timer and 7 other contexts)
Missing class javax.swing.UIManager (referenced from: void org.jetbrains.skiko.Actuals_awtKt.setSystemLookAndFeel())